---
# Nginx and certbot role for Ubuntu

# nginx
# install nginx
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present
  tags:
    - nginx

# add template
- name: Configure Nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ ansible_hostname}}"
    mode: 0644
  tags: 
    - nginx

# linking config
- name: Linking nginx configuration
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ ansible_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ ansible_hostname }}"
    state: link
    owner: root
    group: root
  tags:
    - nginx
  notify:
    - Reload Nginx


# certbot
# install certbot
- name: Add certbot repo
  become: yes
  apt_repository:
    repo: 'ppa:certbot/certbot'
  notify:
    - Update Ubuntu
  tags: 
    - certbot

- name: Install certbot
  become: yes
  apt: 
    name: certbot
    state: latest
  tags: 
    - certbot

# add ssl
- name: Create SSL certificate
  become: yes
  command: certbot certonly --webroot -w /usr/share/nginx/html --domain {{ ansible_hostname }} --email {{ alerts_email }} --agree-tos
  tags:
    - certbot

- name: Secure SSL
  become: yes
  command: sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  tags:
    - certbot
    
# add ssl template part in nginx conf
- name: Configure Nginx
  become: yes
  template:
    src: nginx-ssl.conf.j2
    dest: "/etc/nginx/sites-available/{{ ansible_hostname }}"
    mode: 0644
  tags: 
    - certbot
  notify:
    - Reload Nginx
