---
# handlers file for nginx
- name: Reload Nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Update Ubuntu
  become: yes
  apt:
    name: '*'
    state: present

- name: Update CentOS
  become: yes
  yum:
    name: '*'
    state: present